### ISSUE TITLE
Arduino Fehler

### ISSUE THREAD

**Issue by TimG354** [bjwelker/Raspi-Rollo#4]
Die Library funktioniert für Arduino nicht, was kann ich da tun?

**Comment by Peterkn2001** [comment]
What type of Arduino?
How have you connected your 433MHz receiver to the Arduino?
What exactly does "not working" mean?

**Comment by TimG354** [comment]
I want to use the Library on the Esp866 Demos D1Mini. I downloaded the rc-switch library and replaced the rcswitch.h and rcswitch.cpp file with them from this project. When I compile the sketch there is the error that its not able to find the mySwitch.sendQuadState(""); command.

**Comment by Peterkn2001** [comment]
I don’t understand what you’re trying to achieve.
The `Rollo_Code_Receiver.ino` code is a stand-alone sketch which allows you to decode incoming 433MHz signals.

If you’re using an ESP8266 based board with a recent ESP8266 core installed in your IDE then you’ll need to edit the sketch to change the interrupt handler to avoid an `ISR not in IRAM` error. The changes are described in one of the other open issues.
